### ISSUE TITLE
LSP-pyright: The system Node.js does not meet the requirements

### ISSUE THREAD

**Issue by munkybutt** [sublimelsp/LSP-pyright#100]
Hello, after every update my ST node dependency seems to break.
I do not have a system wide install, so I use the version that LSP downloads to here:
`C:\Users\Sheaky\AppData\Local\Sublime Text 3\Package Storage\lsp_utils\node-runtime\14.17.6`

Normally after each update, I have to delete this folder and have it re-install, but this time that doesn't resolve the issue and this error message in the console persists:
`LSP-pyright: The system Node.js does not meet the requirements: NodeRuntimePATH(node: None, npm: None, version: None)`

**Comment by munkybutt** [comment]
Re-installing LSP-pyright doesn't seem to resolve the issue.
If I delete the ST node install, re-installation fails with:

```
LSP-pyright: Error: Failed installing a local Node.js runtime:
[WinError 5] Access is denied: 'node'
Unable to start subprocess for LSP-pyright
Traceback (most recent call last):
  File "C:\Users\Sheaky\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 333, in start_async
    if plugin_class.needs_update_or_installation():
  File "C:\Users\Sheaky\AppData\Roaming\SUBLIM~1\Packages\LSP_UT~1\st3\lsp_utils\_client_handler\abstract_plugin.py", line 101, in needs_update_or_installation
    server = cls.get_server()
  File "C:\Users\Sheaky\AppData\Roaming\SUBLIM~1\Packages\LSP_UT~1\st3\lsp_utils\npm_client_handler.py", line 100, in get_server
    'skip_npm_install': cls.skip_npm_install,
  File "C:\Users\Sheaky\AppData\Roaming\SUBLIM~1\Packages\LSP_UT~1\st3\lsp_utils\server_npm_resource.py", line 33, in create
    raise Exception('Failed resolving the Node Runtime. Please see Sublime Text console for more information')
Exception: Failed resolving the Node Runtime. Please see Sublime Text console for more information
```
If I run ST as admin, it installs but then breaks again when ST restarts.

**Comment by rchl** [comment]
Possibly some sort of antivirus or something (Windows Defender?) that blocks running the downloaded node instance?

**Comment by rchl** [comment]
> LSP-pyright: The system Node.js does not meet the requirements: NodeRuntimePATH(node: None, npm: None, version: None)

This can be generally ignored since it should still use the local instance. Though in your case the issue is in using the local instance.

**Comment by munkybutt** [comment]
I have uninstalled my anti-virus as I have been meaning to get rid of it for a while, the problem still persists though :(

**Comment by munkybutt** [comment]
Is there a log file I can look through for more information?

**Comment by rchl** [comment]
All the available logs is what you've posted.

The relevant error is `[WinError 5] Access is denied: 'node'` which seems to happen for you when we are trying to run node that was just downloaded. Looks a lot like a permission issue.

Maybe try to run this code in ST console:

```
import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
```

Is it also complaining about access?

If not then maybe screenshot the contents of the directory `C:\Users\Sheaky\AppData\Local\Sublime Text 3\Package Storage\lsp_utils\node-runtime\14.17.6\node`

**Comment by munkybutt** [comment]
Check output seems to run without issue:
```
>>> import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
```

When I started up this morning I noticed a new error in the console after LSP tried to start up again:
```
Unable to start subprocess for LSP-pyright
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
OSError: [WinError 87] The parameter is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sheaky\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 356, in start_async
    transport = create_transport(transport_config, transport_cwd, session)
  File "C:\Users\Sheaky\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 252, in create_transport
    process = start_subprocess()
  File "C:\Users\Sheaky\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 241, in start_subprocess
    return _start_subprocess(config.command, stdin, stdout, subprocess.PIPE, startupinfo, config.env, cwd)
  File "C:\Users\Sheaky\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 323, in _start_subprocess
    cwd=cwd)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
OSError: [WinError 87] The parameter is incorrect
```

And as requested, the SS of the node folder contents:
![image](https://user-images.githubusercontent.com/7100563/142993393-2b00b72b-cbf7-4a0f-afc8-e77848e52491.png)

**Comment by rchl** [comment]
> Check output seems to run without issue:

Not exactly. It doesn't seem like there is any output printed. There should be.

Not quite clear what the `WinError 87` is. Googling mentions that weird characters in the output could cause it or too long paths...

Can you also try running `node.exe --version` from the command line (windows prompt)?

**Comment by jfcherng** [comment]
i am on mobile now. is it needed that appending .exe extension for the executable when calling check_output?

**Comment by rchl** [comment]
Nope. It worked for me without `exe` when trying on Windows.

```
>>> import subprocess; subprocess.check_output(['C:\\Programy\\Sublime4\\Data\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
b'v14.17.6\r\n'
```

**Comment by munkybutt** [comment]
Ah apologies, I was not sure what the expected output was. I figured no news was good news.

If I run it with .exe in the path it works as expected, but without it is the same as before:

```
>>> import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node.exe', '--version'])
b'v14.17.6\r\n'
```

```
>>> import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
import subprocess; subprocess.check_output(['C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node', '--version'])
```

**Comment by rchl** [comment]
Interesting. That could be the issue then. Not sure why it's different on your system though. What Windows version is that?

**Comment by munkybutt** [comment]
Windows 10 Pro
10.0.19042

I just start sublime after restarting my pc and it now seems to work without issue...

```
LSP-pyright: The system Node.js does not meet the requirements: NodeRuntimePATH(node: None, npm: None, version: None)
[lsp_utils] START output of command: "C:\Users\Sheaky\AppData\Local\Sublime Text 3\Package Storage\lsp_utils\node-runtime\14.17.6\node\node.exeC:\Users\Sheaky\AppData\Local\Sublime Text 3\Package Storage\lsp_utils\node-runtime\14.17.6\node\node_modules\npm\bin\npm-cli.jsci--scripts-prepend-node-path=true--verbose--production"
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node.exe',
npm verb cli   'C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'ci',
npm verb cli   '--scripts-prepend-node-path=true',
npm verb cli   '--verbose',
npm verb cli   '--production'
npm verb cli ]
npm info using npm@6.14.15
npm info using node@v14.17.6
npm verb npm-session 74ce922d014ea6c1
npm info prepare initializing installer
npm verb prepare starting workers
npm verb prepare installation prefix: C:\Users\Sheaky\AppData\Local\Sublime Text 3\Package Storage\LSP-pyright\14.17.6\language-server
npm verb prepare using package-lock.json
npm verb checkLock verifying package-lock data
npm info prepare Done in 0.019s
npm verb extractTree extracting dependencies to node_modules/
npm http fetch GET 200 https://registry.npmjs.org/pyright/-/pyright-1.1.189.tgz 3894ms
npm info extractTree Done in 5.522s
npm verb updateJson updating json deps to include _from
npm info updateJson Done in 0.004s
npm verb buildTree finalizing tree and running scripts
npm info lifecycle undefined@undefined~preinstall: undefined@undefined
npm info lifecycle pyright@1.1.189~preinstall: pyright@1.1.189
npm verb linkBins [
npm verb linkBins   { pyright: 'index.js', 'pyright-langserver': 'langserver.index.js' },
npm verb linkBins   'C:\\Users\\Sheaky\\AppData\\Local\\Sublime Text 3\\Package Storage\\LSP-pyright\\14.17.6\\language-server\\node_modules\\.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info lifecycle pyright@1.1.189~install: pyright@1.1.189
npm info lifecycle pyright@1.1.189~postinstall: pyright@1.1.189
npm info lifecycle undefined@undefined~install: undefined@undefined
npm info lifecycle undefined@undefined~postinstall: undefined@undefined
npm info buildTree Done in 0.028s
npm info garbageCollect Done in 0s
npm info lifecycle undefined@undefined~prepublish: undefined@undefined
npm info runScript Done in 0.003s
npm info lifecycle undefined@undefined~prepare: undefined@undefined
npm info runScript Done in 0s
npm verb teardown shutting down workers.
npm info teardown Done in 0.001s
npm info run-scripts total script time: 0.009s
npm info run-time total run time: 5.578s
added 1 packages in 5.578s
npm verb exit [ 0, true ]
npm timing npm Completed in 8755ms
npm info ok
[lsp_utils] Command output END
```

**Comment by munkybutt** [comment]
It all seems to work again ( thanks to the code fairies ) - I guess I will close for now and re-open if it happens again on the next update.
Thanks for the replies!
