### ISSUE TITLE
NoneType object has no attribute 'path'

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-pyright#20]
```
Unable to start LSP-pyright
Traceback (most recent call last):
  File "/home/raoul/.config/sublime-text-3/Packages/LSP/plugin/core/windows.py", line 262, in start_async
    additional_variables = plugin_class.additional_variables()
  File "/home/raoul/.config/sublime-text-3/Installed Packages/LSP-pyright.sublime-package/plugin.py", line 24, in additional_variables
AttributeError: 'NoneType' object has no attribute 'path'
```

**Comment by rchl** [comment]
Works here. Tried both in ST3 and ST4.

Both LSP-pyright and lsp_utils from PC?

**Comment by rchl** [comment]
Error:
```
AttributeError: 'NoneType' object has no attribute 'path'
```
This is the line:
```
        variables["sublime_py_files_dir"] = os.path.dirname(sublime.__file__)
```
It doesn't quite make sense that `os` module has no `path`?

**Comment by rwols** [comment]
I cannot reproduce this now :) very odd

**Comment by jfcherng** [comment]
I seems to encounter this when upgrading the plugin too.
