### ISSUE TITLE
MissingUriError: View 258 has no URI

### ISSUE THREAD

**Issue by giampaolo** [sublimelsp/LSP-pyright#376]
It happens rarely and unfortunately I have no idea how to reproduce it. FWIW, here goes:

```
[LSP-pyright][DEBUG] Due to "dev_environment", new "analysis.extraPaths" is (operation = 'prepend'): ['/opt/sublime_text/Lib/python38', '/opt/sublime_text/Lib/python3', '/home/giampaolo/.config/sublime-text/Lib/python38', '/opt/sublime_text/Packages', '/home/giampaolo/.config/sublime-text/Packages']
Traceback (most recent call last):
  File "/home/giampaolo/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/types.py", line 131, in run
    f()
  File "/home/giampaolo/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/documents.py", line 429, in _on_selection_modified_debounced_async
    self._do_highlights_async()
  File "/home/giampaolo/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/documents.py", line 857, in _do_highlights_async
    params = cast(DocumentHighlightParams, text_document_position_params(self.view, point))
  File "/home/giampaolo/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/views.py", line 271, in text_document_position_params
    return {"textDocument": text_document_identifier(view), "position": position(view, location)}
  File "/home/giampaolo/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/views.py", line 228, in text_document_identifier
    uri = uri_from_view(view_or_uri)
  File "/home/giampaolo/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/views.py", line 221, in uri_from_view
    raise MissingUriError(view.id())
LSP.plugin.core.views.MissingUriError: View 258 has no URI
```

**Comment by jfcherng** [comment]
I doubt that this is a LSP-pyright issue.
